### ISSUE TITLE
Extended Primer

### ISSUE THREAD

**Issue by nitin42** [yatharthk/frontend-computer-science#1]
👍   for the list. Thinking about writing a primer on these topics! What do you say?

**Comment by yatharthx** [comment]
Thanks @nitin42 . Well, I thought about something like that. But that wasn't exactly a primer. Probably helpful links could be a better workout over here. Not sure. Can you tell me what exactly you're thinking in terms of primer? To what extent in detail?

**Comment by nitin42** [comment]
Sure I can tell you what I am thinking exactly. The main problem for us (frontend developers) is to have good grasp over the data structures and some other CS fundamentals (AST, Algorithms) when it comes to writing some tools like parsers, plugins or loaders. Learning all these things at first can be very daunting for one who is comfortable writing the frontend code which I don't think so involves math or calculations. A single aggregated source with decent content about these topics can be helpful.

**Comment by nitin42** [comment]
Something like blog posts or a GitBook could be better. Because I think they are excellent way of spreading the knowledge. A reliable succinct resource which would be kept open so that anybody can improve it further and anybody can access it freely.

**Comment by yatharthx** [comment]
I got you. So first things first. We've actually got some good content available on the Internet. So creating/writing new content isn't very smart I guess. Rather we can use the same resources/links and devs can explore things as and to what extent they want. And sure, I agree with you on the Gitbook thingy.

**Comment by nitin42** [comment]
I think creating a list of aggregated resources is also a good option. Let me know about your thoughts on GitBook.

**Comment by yatharthx** [comment]
Sure @nitin42 . We shall go ahead with GitBook. Please frame your thoughts/ideas/whatever as a markdown over here. We can discuss over it and see how can we frame the content in best possible way.

PS: I'm running a little busy for next 2-3 days. I'll too start working on the content, thereafter.

**Comment by nitin42** [comment]
I am also working on a project of mine. I will let you know about my ideas but only after 3-4 days.
